using NUnit.Framework;

namespace Day10
{
    [TestFixture]
    public class Tests
    {
        [Test]
        [TestCase(new string[] {
"<position=< 9,  1> velocity=< 0,  2>",
"<position=< 7,  0> velocity=<-1,  0>",
"<position=< 3, -2> velocity=<-1,  1>",
"<position=< 6, 10> velocity=<-2, -1>",
"<position=< 2, -4> velocity=< 2,  2>",
"<position=<-6, 10> velocity=< 2, -2>",
"<position=< 1,  8> velocity=< 1, -1>",
"<position=< 1,  7> velocity=< 1,  0>",
"<position=<-3, 11> velocity=< 1, -2>",
"<position=< 7,  6> velocity=<-1, -1>",
"<position=<-2,  3> velocity=< 1,  0>",
"<position=<-4,  3> velocity=< 2,  0>",
"<position=<10, -3> velocity=<-1,  1>",
"<position=< 5, 11> velocity=< 1, -2>",
"<position=< 4,  7> velocity=< 0, -1>",
"<position=< 8, -2> velocity=< 0,  1>",
"<position=<15,  0> velocity=<-2,  0>",
"<position=< 1,  6> velocity=< 1,  0>",
"<position=< 8,  9> velocity=< 0, -1>",
"<position=< 3,  3> velocity=<-1,  1>",
"<position=< 0,  5> velocity=< 0, -1>",
"<position=<-2,  2> velocity=< 2,  0>",
"<position=< 5, -2> velocity=< 1,  2>",
"<position=< 1,  4> velocity=< 2,  1>",
"<position=<-2,  7> velocity=< 2, -2>",
"<position=< 3,  6> velocity=<-1, -1>",
"<position=< 5,  0> velocity=< 1,  0>",
"<position=<-6,  0> velocity=< 2,  0>",
"<position=< 5,  9> velocity=< 1, -2>",
"<position=<14,  7> velocity=<-2,  0>",
"<position=<-3,  6> velocity=< 2, -1>"
        }
        , 0, new string[] {
"........#.............",
"................#.....",
".........#.#..#.......",
"......................",
"#..........#.#.......#",
"...............#......",
"....#.................",
"..#.#....#............",
".......#..............",
"......#...............",
"...#...#.#...#........",
"....#..#..#.........#.",
".......#..............",
"...........#..#.......",
"#...........#.........",
"...#.......#.........."
        }, TestName = "Map 0")]
        [TestCase(new string[] {
"<position=< 9,  1> velocity=< 0,  2>",
"<position=< 7,  0> velocity=<-1,  0>",
"<position=< 3, -2> velocity=<-1,  1>",
"<position=< 6, 10> velocity=<-2, -1>",
"<position=< 2, -4> velocity=< 2,  2>",
"<position=<-6, 10> velocity=< 2, -2>",
"<position=< 1,  8> velocity=< 1, -1>",
"<position=< 1,  7> velocity=< 1,  0>",
"<position=<-3, 11> velocity=< 1, -2>",
"<position=< 7,  6> velocity=<-1, -1>",
"<position=<-2,  3> velocity=< 1,  0>",
"<position=<-4,  3> velocity=< 2,  0>",
"<position=<10, -3> velocity=<-1,  1>",
"<position=< 5, 11> velocity=< 1, -2>",
"<position=< 4,  7> velocity=< 0, -1>",
"<position=< 8, -2> velocity=< 0,  1>",
"<position=<15,  0> velocity=<-2,  0>",
"<position=< 1,  6> velocity=< 1,  0>",
"<position=< 8,  9> velocity=< 0, -1>",
"<position=< 3,  3> velocity=<-1,  1>",
"<position=< 0,  5> velocity=< 0, -1>",
"<position=<-2,  2> velocity=< 2,  0>",
"<position=< 5, -2> velocity=< 1,  2>",
"<position=< 1,  4> velocity=< 2,  1>",
"<position=<-2,  7> velocity=< 2, -2>",
"<position=< 3,  6> velocity=<-1, -1>",
"<position=< 5,  0> velocity=< 1,  0>",
"<position=<-6,  0> velocity=< 2,  0>",
"<position=< 5,  9> velocity=< 1, -2>",
"<position=<14,  7> velocity=<-2,  0>",
"<position=<-3,  6> velocity=< 2, -1>"
        },
        1, new string[] {
"......................",
"......................",
"..........#....#......",
"........#.....#.......",
"..#.........#......#..",
"......................",
"......#...............",
"....##.........#......",
"......#.#.............",
".....##.##..#.........",
"........#.#...........",
"........#...#.....#...",
"..#...........#.......",
"....#.....#.#.........",
"......................",
"......................",
        }, TestName = "Map 1")]
        [TestCase(new string[] {
"<position=< 9,  1> velocity=< 0,  2>",
"<position=< 7,  0> velocity=<-1,  0>",
"<position=< 3, -2> velocity=<-1,  1>",
"<position=< 6, 10> velocity=<-2, -1>",
"<position=< 2, -4> velocity=< 2,  2>",
"<position=<-6, 10> velocity=< 2, -2>",
"<position=< 1,  8> velocity=< 1, -1>",
"<position=< 1,  7> velocity=< 1,  0>",
"<position=<-3, 11> velocity=< 1, -2>",
"<position=< 7,  6> velocity=<-1, -1>",
"<position=<-2,  3> velocity=< 1,  0>",
"<position=<-4,  3> velocity=< 2,  0>",
"<position=<10, -3> velocity=<-1,  1>",
"<position=< 5, 11> velocity=< 1, -2>",
"<position=< 4,  7> velocity=< 0, -1>",
"<position=< 8, -2> velocity=< 0,  1>",
"<position=<15,  0> velocity=<-2,  0>",
"<position=< 1,  6> velocity=< 1,  0>",
"<position=< 8,  9> velocity=< 0, -1>",
"<position=< 3,  3> velocity=<-1,  1>",
"<position=< 0,  5> velocity=< 0, -1>",
"<position=<-2,  2> velocity=< 2,  0>",
"<position=< 5, -2> velocity=< 1,  2>",
"<position=< 1,  4> velocity=< 2,  1>",
"<position=<-2,  7> velocity=< 2, -2>",
"<position=< 3,  6> velocity=<-1, -1>",
"<position=< 5,  0> velocity=< 1,  0>",
"<position=<-6,  0> velocity=< 2,  0>",
"<position=< 5,  9> velocity=< 1, -2>",
"<position=<14,  7> velocity=<-2,  0>",
"<position=<-3,  6> velocity=< 2, -1>"
        },
        2, new string[] {
"......................",
"......................",
"......................",
"..............#.......",
"....#..#...####..#....",
"......................",
"........#....#........",
"......#.#.............",
".......#...#..........",
".......#..#..#.#......",
"....#....#.#..........",
".....#...#...##.#.....",
"........#.............",
"......................",
"......................",
"......................"
        }, TestName = "Map 2")]
        [TestCase(new string[] {
"<position=< 9,  1> velocity=< 0,  2>",
"<position=< 7,  0> velocity=<-1,  0>",
"<position=< 3, -2> velocity=<-1,  1>",
"<position=< 6, 10> velocity=<-2, -1>",
"<position=< 2, -4> velocity=< 2,  2>",
"<position=<-6, 10> velocity=< 2, -2>",
"<position=< 1,  8> velocity=< 1, -1>",
"<position=< 1,  7> velocity=< 1,  0>",
"<position=<-3, 11> velocity=< 1, -2>",
"<position=< 7,  6> velocity=<-1, -1>",
"<position=<-2,  3> velocity=< 1,  0>",
"<position=<-4,  3> velocity=< 2,  0>",
"<position=<10, -3> velocity=<-1,  1>",
"<position=< 5, 11> velocity=< 1, -2>",
"<position=< 4,  7> velocity=< 0, -1>",
"<position=< 8, -2> velocity=< 0,  1>",
"<position=<15,  0> velocity=<-2,  0>",
"<position=< 1,  6> velocity=< 1,  0>",
"<position=< 8,  9> velocity=< 0, -1>",
"<position=< 3,  3> velocity=<-1,  1>",
"<position=< 0,  5> velocity=< 0, -1>",
"<position=<-2,  2> velocity=< 2,  0>",
"<position=< 5, -2> velocity=< 1,  2>",
"<position=< 1,  4> velocity=< 2,  1>",
"<position=<-2,  7> velocity=< 2, -2>",
"<position=< 3,  6> velocity=<-1, -1>",
"<position=< 5,  0> velocity=< 1,  0>",
"<position=<-6,  0> velocity=< 2,  0>",
"<position=< 5,  9> velocity=< 1, -2>",
"<position=<14,  7> velocity=<-2,  0>",
"<position=<-3,  6> velocity=< 2, -1>"
        },
        3, new string[] {
"......................",
"......................",
"......................",
"......................",
"......#...#..###......",
"......#...#...#.......",
"......#...#...#.......",
"......#####...#.......",
"......#...#...#.......",
"......#...#...#.......",
"......#...#...#.......",
"......#...#..###......",
"......................",
"......................",
"......................",
"......................"
        }, TestName = "Map 3")]
        [TestCase(new string[] {
"<position=< 9,  1> velocity=< 0,  2>",
"<position=< 7,  0> velocity=<-1,  0>",
"<position=< 3, -2> velocity=<-1,  1>",
"<position=< 6, 10> velocity=<-2, -1>",
"<position=< 2, -4> velocity=< 2,  2>",
"<position=<-6, 10> velocity=< 2, -2>",
"<position=< 1,  8> velocity=< 1, -1>",
"<position=< 1,  7> velocity=< 1,  0>",
"<position=<-3, 11> velocity=< 1, -2>",
"<position=< 7,  6> velocity=<-1, -1>",
"<position=<-2,  3> velocity=< 1,  0>",
"<position=<-4,  3> velocity=< 2,  0>",
"<position=<10, -3> velocity=<-1,  1>",
"<position=< 5, 11> velocity=< 1, -2>",
"<position=< 4,  7> velocity=< 0, -1>",
"<position=< 8, -2> velocity=< 0,  1>",
"<position=<15,  0> velocity=<-2,  0>",
"<position=< 1,  6> velocity=< 1,  0>",
"<position=< 8,  9> velocity=< 0, -1>",
"<position=< 3,  3> velocity=<-1,  1>",
"<position=< 0,  5> velocity=< 0, -1>",
"<position=<-2,  2> velocity=< 2,  0>",
"<position=< 5, -2> velocity=< 1,  2>",
"<position=< 1,  4> velocity=< 2,  1>",
"<position=<-2,  7> velocity=< 2, -2>",
"<position=< 3,  6> velocity=<-1, -1>",
"<position=< 5,  0> velocity=< 1,  0>",
"<position=<-6,  0> velocity=< 2,  0>",
"<position=< 5,  9> velocity=< 1, -2>",
"<position=<14,  7> velocity=<-2,  0>",
"<position=<-3,  6> velocity=< 2, -1>"
        },
        4, new string[] {
"......................",
"......................",
"......................",
"............#.........",
"........##...#.#......",
"......#.....#..#......",
".....#..##.##.#.......",
".......##.#....#......",
"...........#....#.....",
"..............#.......",
"....#......#...#......",
".....#.....##.........",
"...............#......",
"...............#......",
"......................",
"......................"
        }, TestName = "Map 4")]
        public void Map(string[] inputs, int time, string[] expected)
        {
            Program.Parse(inputs);
            Program.Simulate(time);
            Assert.That(Program.MapOutput(), Is.EqualTo(expected));
        }
    }
}
